import { useMemo, useState } from 'react';
import {
  Download, RefreshCw, FileText, CheckCircle2, XCircle, IndianRupee,
  Percent, AlertTriangle, TrendingUp,
} from 'lucide-react';
import { useApi } from '../hooks/useApi';
import { getReports } from '../api';
import { useApp } from '../context/AppContext';
import { useToast } from '../context/ToastContext';
import { Panel } from '../components/ui/Panel';
import { Segmented } from '../components/ui/Segmented';
import { StatCard } from '../components/ui/StatCard';
import { Button } from '../components/ui/Button';
import { ErrorState } from '../components/ui/ErrorState';
import { WaitingState } from '../components/ui/EmptyState';
import { REPORT_TYPES } from '../types';
import { fmtINR, fmtPct, fmtCompact, fmtDateTime } from '../utils/format';

export function Reports() {
  const { dateRange } = useApp();
  const toast = useToast();
  const [type, setType] = useState('daily');

  const api = useApi(() => getReports({ type, from: dateRange.from, to: dateRange.to }), [type, dateRange]);
  const report = api.data || null;
  const st = useMemo(() => {
    if (!report) return null;
    const failures = report.failure_rate ?? report.metrics?.failure_rate;
    return {
      volume: report.payment_volume ?? report.metrics?.payment_volume,
      successRate: report.success_rate ?? report.metrics?.success_rate,
      failureRate: failures,
      amountLost: report.amount_lost ?? report.metrics?.amount_lost,
      amountRecovered: report.amount_recovered ?? report.metrics?.amount_recovered,
      recoveryRate: report.recovery_rate ?? report.metrics?.recovery_rate,
      topCauses: report.top_failure_causes ?? report.metrics?.top_failure_causes ?? [],
    };
  }, [report]);

  const current = REPORT_TYPES.find((r) => r.key === type);

  const download = () => {
    if (!report) {
      toast('Nothing to download', 'info', { description: 'A report must be generated by the backend first.' });
      return;
    }
    const blob = new Blob([JSON.stringify({ type, from: dateRange.from, to: dateRange.to, data: report }, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pulseops-report-${type}-${dateRange.from}-${dateRange.to}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast('Report downloaded', 'success', { description: a.download });
  };

  return (
    <div className="page">
      <Panel
        title="Generate report"
        subtitle="Pick a report type and period — the backend compiles it from live payment events."
        actions={
          <>
            <Button variant="outline" size="sm" onClick={api.refresh}>
              <RefreshCw size={13} /> Generate
            </Button>
            <Button size="sm" onClick={download}>
              <Download size={13} /> Download
            </Button>
          </>
        }
      >
        <Segmented options={REPORT_TYPES.map((r) => ({ value: r.key, label: r.label }))} value={type} onChange={setType} />
        <div className="report-desc">
          <strong>{current.label}</strong>
          <span>{current.description} · Range {dateRange.from} → {dateRange.to}</span>
        </div>

        {api.loading ? (
          <WaitingState title="Compiling report…" />
        ) : api.networkError ? (
          <ErrorState error={api.error} onRetry={api.refresh} />
        ) : api.unavailable ? (
          <WaitingState
            title="Report endpoint pending"
            description={`GET /api/reports?type=${type} is not implemented yet. The report panel below will populate with your live metrics (volume, success rate, failure rate, amount lost/recovered, top causes) once it is live.`}
          />
        ) : !report ? (
          <WaitingState title="No report data" description="The backend returned an empty report for this period." />
        ) : (
          <>
            <section className="stats-grid">
              <StatCard label="Payment volume" value={st.volume != null ? fmtCompact(st.volume) : '—'} sub="processsed in period" icon={IndianRupee} />
              <StatCard label="Success rate" value={st.successRate != null ? fmtPct(st.successRate) : '—'} sub="of all attempts" icon={CheckCircle2} />
              <StatCard label="Failure rate" value={st.failureRate != null ? fmtPct(st.failureRate) : '—'} sub="of all attempts" icon={XCircle} />
              <StatCard label="Amount lost" value={st.amountLost != null ? fmtINR(st.amountLost) : '—'} sub="to failures" icon={AlertTriangle} />
              <StatCard label="Amount recovered" value={st.amountRecovered != null ? fmtINR(st.amountRecovered) : '—'} sub="via recovery actions" icon={TrendingUp} />
              <StatCard label="Recovery rate" value={st.recoveryRate != null ? fmtPct(st.recoveryRate) : '—'} sub="recovered / recoverable" icon={Percent} />
            </section>

            <div className="report-meta">
              <span className="chip"><FileText size={12} /> {current.label}</span>
              <span className="muted">Generated {fmtDateTime(report.generated_at || report.created_at)}</span>
            </div>

            <div className="report-section">
              <h4>Top failure causes</h4>
              {st.topCauses && st.topCauses.length > 0 ? (
                <div className="bar-list">
                  {st.topCauses.map((c, i) => (
                    <div className="bar-legend-row" key={i}>
                      <span className="chip">{c.reason || c.name || c.cause}</span>
                      <div className="bar-track"><div className="bar-fill" style={{ width: `${Math.min(c.count ?? c.value ?? 100, 100)}%` }} /></div>
                      <strong>{c.count != null ? fmtCompact(c.count) : `${c.percent ?? c.value}%`}</strong>
                    </div>
                  ))}
                </div>
              ) : (
                <WaitingState title="No failure data" description="Top failure causes appear once the backend compiles the report." />
              )}
            </div>
          </>
        )}
      </Panel>
    </div>
  );
}